use std::str::FromStr;
use crate::ast::{LiteralValue, ExpressionStaticType};

grammar;

pub LiteralValue: LiteralValue = {
  r"[0-9]+" => LiteralValue::IntLiteral(i32::from_str(<>).unwrap()),
  "true" => LiteralValue::BoolLiteral(true),
  "false" => LiteralValue::BoolLiteral(false),
}

pub ExpressionStaticType: ExpressionStaticType = {
  "void" => ExpressionStaticType::VoidType,
  "int" => ExpressionStaticType::IntType,
  "bool" => ExpressionStaticType::BoolType,
}
